name: inghub_pomo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  go_router: ^14.2.8
  http: ^1.2.2
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  provider: ^6.1.2
  pub_semver: ^2.1.4
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansKR
      fonts: 
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Bold.ttf
          weight: 700
        # - asset: assets/fonts/noto_sans_kr/NotoSansKR-ExtraBold.ttf
        #   weight: 800

  